@extends('layouts.pageLayout')
@section('content')
    <div class="container my-3">
        <div class="row">
           
            <div class="col-md">
                 <h3>Terms and Condition</h3>
                <p>
                    These standard terms of sale ("terms of sale") is an electronic record in the form of an electronic contract formed under information technology act, 2000 and rules made thereunder and the amended provisions pertaining to electronic documents / records in various statutes as amended by the information technology act, 2000. These terms of sale does not require any physical, electronic or digital signature.
                </p>
                <p>
                    These terms of sale is a legally binding document between buyer and seller where the seller has made the offer to sell the products by listing the same on the website and buyer has accepted such offer of the seller by agreeing to buy the product so offered on the website. These terms of sale will be effective and binding on the seller upon seller's advertising, exhibiting and creating a listing of the product on the website, and shall be effective and binding on the buyer upon buyer agreeing to purchase the products so listed by the seller.
                </p>
                <p>
                    In these terms of sale, a user (whether guest user or registered user) who purchase various products (as defined below) from the seller on the website located at the url www.kidoworldstore.in and mobile application under the name and style "kid-o-world" (the website) is referred to as "buyer" and the seller is referred to as an individual or any legal entity who list, advertise, exhibit, offers to sell, make available, market, sale and deliver any products through the website to the buyer (referred to as "seller"). These terms of sale describe, inter alia, the terms of offer for sale/sale, acceptance of offer for sale by buyer and the purchase of goods and services ("products") through the website from the seller. These terms of sale also contains certain statements and disclaimers made by Kid-O-World private limited ("Kid-O-World") which shall be binding on buyer and seller, as the case may be. Sometimes both buyer and seller are collectively referred to as "you" with its grammatical variations and cognate expressions.
                </p>
                <p>
                    Please read these terms of sale carefully before listing any product or before purchasing any products. These terms of sale are in addition to various agreements, terms, privacy policy, terms of use and all other policies of the website. Seller may include additional or conflicting terms and conditions of sale in the product listing or product description as made available on the website ('additional terms of sale'). If there is any conflict between these terms of sale and the additional terms of sale, the additional terms of sale shall take precedence to the extent of such conflict and in relation to that sale. If a seller does not agree with these terms of sale, please do not list of make any offer for sale of any products on the website and if a buyer does not agree to these terms of sale and additional terms of sale, please do not buy or attempt to buy any product listed on the website.
                </p>
                <p>
                    These terms of sale are subject to revision at any time and hence both buyers and sellers are requested to carefully read these terms of sale from time to time before listing any product or before making any purchase of the products. The revised terms of sale shall be made available on the website. If such a facility is provided, you may determine when these terms of sale were last modified by referring to the "last updated" legend provided above.
                </p>
                    <p>
                        You are requested to regularly visit the website to view the most current terms of sale. It shall be your responsibility to check these terms of sale periodically for changes and buyer should also check additional terms of
                    </p>
                <p>
                    Sale of the seller on the product listing. You may be asked to provide your specific consent to any updates in a specified manner before any further use of the website and related services. If no separate consent is sought, your continued use of the website following such changes and modifications to the website or these terms of sale will constitute your acceptance of such changes or modifications.
                </p>
                <h5 class="my-1">Offer and acceptance of the product
                </h5>
                <p>
                    1.1 The seller hereby makes an offer to sell the products listed by seller on the website and the buyer upon agreeing to purchase the products so listed by the seller hereby accepts such offer to sell by the seller. Accordingly, the contract for sale of the product is be a bipartite contract between buyer and the seller. Kid-O-World is not a third party beneficiary under such bipartite contract. The buyer understands and agrees that the offer for sale of the product by the seller is not an absolute or an unconditional offer. Such offer to sale by the seller is subject to repudiation by the seller at any time before the delivery of the product to the buyer and without any obligation to assign or provide any reason for such repudiation and without any consent from the buyer and without any liability or any obligation towards the buyer. The seller and buyer understand and agree that Kid-O-World has the right to cancel any sale transaction, listing or acceptance (i) for any reason in accordance with the seller agreement, these terms of sale, website terms of use, privacy policy or under any contract or policy between Kid-O-World on one hand and the seller or the buyer on the other hand, or (ii) under an order or instruction from any statutory, quasi-judicial or judicial authority.
                </p>
                <h5 class="my-2">Product(s)</h5>
                <p>
                    2.1 Kid-o-world also respects the intellectual property rights of all entities. If you believe that your intellectual property rights have been violated in any manner, please fill out and submit the notice of infringement of intellectual property form ("ip infringement notice") provided in the annexure below. Please send the duly filed out ip infringement notice via email to grievanceofficer@kid-o-world.com. Any incomplete or improperly filled out document may not be considered.
                </p>
                <p>
                    2.2 The availability of the product under the offer to sell is subject to change without notice prior to the purchase of the product by the buyer. However, there may be circumstances where the product may not be available to be delivered to the buyer after the purchase transaction. In such an event, seller may cancel or instruct Kid-O-World to cancel such purchase transaction without any recourse to buyer and without any liability to the seller or to Kid-O-World. If buyer's order is so cancelled, after the payment has been processed, the said amount will be reversed / remitted to the buyer either to the bank account provided by the buyer for such reversal, or to the payment instrument of the buyer from which payment was made, or to any pre-paid payment instrument account of the buyer. Kid-O-World shall have the sole discretion to determine the mode of reversal from the above options.
                </p>
                <p>
                    2.3 With respect to the sale of product by seller to the buyer, the seller hereby represents and warrants to the buyer that:
                    Seller has the right to sell the products to the buyer on or through the website;
                    Buyer shall have and enjoy quiet possession of the products;
                    Products shall be free from any charge or encumbrance in favor of third party;
                    Buyer shall be entitled to all the warranties and other collaterals applicable to the product or as generally made available by the manufacturer or seller of the product;
                    Product shall meet the description and specifications as provided on the website.
                </p>
                <h5>Pricing information</h5>
                <p>
                    1.1 The selling price of the product is subject to change without notice prior to the purchase of the product by the buyer. The selling price is provided on the website on 'as is' basis as provided by the seller. Due to technical reasons there may be errors in selling price which may be corrected by the seller at any time and any acceptance of offer of sale by the buyer of the products subject to such faulty selling price shall, subject to discretion of the seller, not be a valid acceptance and such transaction can be avoided by the seller.
                    2.2 All prices are inclusive of vat unless stated otherwise.
                </p>
                <h5>Delivery of the product</h5>
                <p>
                    4.1 There are various delivery models for delivery of purchased product to the buyer, as decided by the seller. The risk of any damage, loss or deterioration of the products during the course or delivery or during transit shall be on the seller and not on the buyer. Seller represent and warrant that the products being delivered are not faulty and are exactly those products which are listed and advertised by seller on the website and purchased by the buyer and meet all descriptions and specifications as provided on the website.<br>
                    4.2 Buyer's shipping address, pin code will be verified with the database of website before a buyer proceed to pay for buyer's purchase. In the event buyer's order is not serviceable by logistic service providers or by seller or the delivery address is not located in an area that is covered under the order confirmation form, buyer may provide an alternate shipping address on which the product can be delivered by the logistics service provider or by the seller.
                </p>
                <p>
                    4.3 Please note that there is no guaranteed dispatch time and any information about the dispatch time is estimate only and should not be relied upon as such. Therefore, time is not the essence of the bi-partite contract between the buyer and the seller for purchase and sale of product on or through the website. However, the product shall not be delivered to the buyer unless the buyer makes the payment of the purchase of product.
                   <br> 4.4 Buyer shall be bound to take delivery of the products purchased by the buyer that are said to be in a deliverable state. Where buyer neglects or refuses to accept the delivery of the products ordered by the buyer, the buyer may be liable to the seller for such non-acceptance and shall further be liable to Kid-O-World for any loss of any fee or charges that Kid-O-World and its third parties shall have earned from the seller if such delivery or transaction should have been completed. Buyer acknowledges that such damages or loss to Kid-O-World and its third parties are not consequential or indirect.
                    <br>4.5 The title in the products and other rights and interest in the products shall directly pass on to the buyer from seller upon delivery of such product and upon full payment of price of the product. Upon delivery, the buyer is deemed to have accepted the products. The risk of loss shall pass on to the buyer upon delivery of product.
                </p>
                <h5>Return policy for products</h5>
                <p>
                    5.1 Buyer's product related complainant for refund or replacement will the processed in accordance with the our r&r policy available at  www.kidoworldstore.in Both buyer and seller agree to this r&r policy (refunds & replacement). However, in the event of false, frivolous or baseless complaints regarding the delivery or quality of the products, the buyer will not be eligible for refund or replacement.
                <br>    5.2 Before accepting delivery of any product, the buyer shall reasonably ensure that the product's packaging is not damaged or tampered.
                <br>    5.3 The return process of a product may be subject to additional terms depending on the nature and category of the product. Any such additional terms may be specified on the website or be intimated by the seller at the time of purchase of the product.
                <br>    5.4 In the event the return of a product is duly accepted by seller, the value of such product, as originally paid by buyer during acceptance of product, will either be refunded to buyer either to the bank account provided by the buyer for such refund, or to the payment instrument of the buyer from which payment was made, or to any pre-paid payment instrument account of the buyer. Kid-O-World shall have the sole discretion to determine the mode of reversal from the above options.
                 <br>   5.5 Buyer agrees that if the returned product is not accepted by the seller then Kid-O-World shall have the right liquidate or sell those products and give all the valid title, rights and interests including warranties and other collaterals and benefits associated with those products (as the buyer would have received from the seller) to any third party to whom those products are sold.
                </p>
                <h5>Cancellation of transaction / orders</h5>
                <p>
                    6.1 <strong>Cancellation by seller:</strong> there may be certain orders that seller is unable to accept and has the right to cancel either by the seller directly or seller can instruct Kid-O-World to cancel such order. Seller reserves the right, at its sole discretion, to refuse or cancel any order for any reason whatsoever. Some situations that may result in buyer's order being cancelled include, without limitation, non-availability of the product or quantities ordered by buyer or inaccuracies or errors in pricing information. Seller may also require additional verifications or information before processing any order. All such cancellation shall be without any recourse to buyer and without any liability to the seller or to Kid-O-World. If buyer's order is so cancelled, after the payment has been processed, the said amount will be reversed / remitted to the buyer either to the bank account provided by the buyer for such reversal, or to the payment instrument of the buyer from which payment was made, or to any pre-paid payment instrument account of the buyer. Kid-O-World shall have the sole discretion to determine the mode of reversal from the above options. In the event a promotional code given by Kid-O-World is used for the purchase of the product, the amount under such promotional code shall not be refunded in case of cancellation of order. The above is the sole remedy of the buyer and the sole liability of the seller and sole responsibility of Kid-O-World for any cancellation of the purchase order by the seller or otherwise other than by the buyer.
                   <br> 6.2 <strong>Cancellation by the buyer:</strong> in case of requests for order cancellations, seller reserves the right to accept or reject requests for order cancellations for any reason whatsoever. As part of usual business practice, if seller receives a cancellation notice and the order has not been processed, seller may cancel the order and refund the entire amount to buyer within a reasonable period of time. Seller will not be able to cancel orders that have already been processed by the seller. Buyer agrees not to dispute the decision made by seller and accept seller's decision regarding the cancellation.
                   <br> 6.3 <strong>Set-off of any benefits availed by the buyer:</strong> in case the buyer has availed any benefit under any marketing or promotions provided by Kid-O-World in relation to the product for which the order has been cancelled by the buyer or by the seller, buyer agrees and authorizes Kid-O-World private limited to recover such benefits from the buyer or set-off the same from any refunds to the buyer.
                </p>
                <h5>Governing law</h5>
                <p>
                    These terms of sale shall be governed in accordance with the laws of india without reference to conflict of laws principles. You acknowledge that these terms of sale are solely for your benefit. It is not for the benefit of any other person, except for your successors and permitted assigns.
                </p>
                <h5>Disclaimer by Kid-O-World</h5>
                1 Kid-O-World's role is that of an intermediary in the form of an online marketplace and is limited to managing the website to enable seller to exhibit, advertise, display, make available and offer to sell the products and to enable buyer to purchase the products so offered, and other incidental services to facilitate the transactions between sellers and the buyers. Accordingly, the contract for sale of any of the products shall be a bipartite contract between seller and the buyer. At no time shall Kid-O-World have any obligations or liabilities in respect of such contract nor shall Kid-O-World hold any title in the products. The title in the products and other rights and interest in the products shall directly pass to the buyer from the seller.
              <br>  2 These terms of sale shall not amend or modify any agreements, contracts, terms or policies between the buyer or seller on one hand and Kid-O-World on the other hand.
                <br>   3 Kid-O-World does not control, endorse or accept responsibility for any product (including but not limited to product catalogues) offered by sellers accessible through the website or any linked sites. Kid-O-World makes no representations or warranties whatsoever about, and shall not be liable for, the seller or any such third parties, their products including representations relating to merchantabiligy, fitness of a product or service for a particular purpose, and non-infringement of third party intellectual property rights. Any transactions that buyer may have with such third parties are at buyer's own risk. The products shall be subject to seller's terms and conditions for warranty, service and maintenance, and Kid-O-World does not accept any responsibility for the same. Kid-O-World also does not accept any responsibility for the usage of the products by the buyer.
                <br>  4 Kid-O-World specifically disclaims any liability with regard to any illegal, infringing, fake, duplicate, spurious, defective or counterfeit, refurbished, expired products purchased by buyer from the seller and Kid-O-World shall not assume any liability if the product purchased or availed by buyer from the seller is not exactly as per specifications detailed in the purchase confirmation order.
                <br>  5. Kid-O-World is in no way responsible or liable for the offer for sale or sale of the product by the seller to the buyer, its delivery, the warranty terms (if any) related to the product and the return, refund or cancellation of purchase of any products.
                <br>  6. Kid-O-World does not warrant that the sale price provided by the seller of the product is accurate, proper and valid. Any error in the sale price shall be solely attributed to the seller and not to Kid-O-World. Prices, product description and availability of the product are seller's responsibility.
                <br>  7. Buyer expressly acknowledges that the seller selling the defective product will be responsible to buyer for any claims that buyer may have in relation to such defective product and Kid-O-World shall not in any manner be held liable for the same.
                <br>  8. Kid-O-World shall not assume any liability for the non-availability of the product, delivery of the product directly by the seller and the installation of the product where required.
            </div>
        </div>
    </div>
    @endsection
